import { TimeOption } from '@grafana/data';

import { ComboboxOption } from '../Combobox/Combobox';

export const quickOptions: TimeOption[] = [
  { from: 'now-5m', to: 'now', display: 'Последние 5 минут' },
  { from: 'now-15m', to: 'now', display: 'Последние 15 минут' },
  { from: 'now-30m', to: 'now', display: 'Последние 30 минут' },
  { from: 'now-1h', to: 'now', display: 'Последний час' },
  { from: 'now-3h', to: 'now', display: 'Последние 3 часа' },
  { from: 'now-6h', to: 'now', display: 'Последние 6 часов' },
  { from: 'now-12h', to: 'now', display: 'Последние 12 часов' },
  { from: 'now-24h', to: 'now', display: 'Последние 24 часа' },
  { from: 'now-2d', to: 'now', display: 'Последние 2 дня' },
  { from: 'now-7d', to: 'now', display: 'Последние 7 дней' },
  { from: 'now-30d', to: 'now', display: 'Последние 30 дней' },
  { from: 'now-90d', to: 'now', display: 'Последние 90 дней' },
  { from: 'now-6M', to: 'now', display: 'Последние 6 месяцев' },
  { from: 'now-1y', to: 'now', display: 'Последний 1 год' },
  { from: 'now-2y', to: 'now', display: 'Последние 2 года' },
  { from: 'now-5y', to: 'now', display: 'Последние 5 лет' },
  { from: 'now-1d/d', to: 'now-1d/d', display: 'Yesterday' },
  { from: 'now-2d/d', to: 'now-2d/d', display: 'Day before yesterday' },
  { from: 'now-7d/d', to: 'now-7d/d', display: 'This day last week' },
  { from: 'now-1w/w', to: 'now-1w/w', display: 'Previous week' },
  { from: 'now-1M/M', to: 'now-1M/M', display: 'Previous month' },
  { from: 'now-1Q/fQ', to: 'now-1Q/fQ', display: 'Previous fiscal quarter' },
  { from: 'now-1y/y', to: 'now-1y/y', display: 'Previous year' },
  { from: 'now-1y/fy', to: 'now-1y/fy', display: 'Previous fiscal year' },
  { from: 'now/d', to: 'now/d', display: 'Сегодня' },
  { from: 'now/d', to: 'now', display: 'Сегодняшний день' },
  { from: 'now/w', to: 'now/w', display: 'Это неделя' },
  { from: 'now/w', to: 'now', display: 'This week so far' },
  { from: 'now/M', to: 'now/M', display: 'Этот месяц' },
  { from: 'now/M', to: 'now', display: 'This month so far' },
  { from: 'now/y', to: 'now/y', display: 'Этот год' },
  { from: 'now/y', to: 'now', display: 'This year so far' },
  { from: 'now/fQ', to: 'now', display: 'This fiscal quarter so far' },
  { from: 'now/fQ', to: 'now/fQ', display: 'Текущий финансовый квартал' },
  { from: 'now/fy', to: 'now', display: 'This fiscal year so far' },
  { from: 'now/fy', to: 'now/fy', display: 'Текущий финансовый год' },
];

export const monthOptions: Array<ComboboxOption<number>> = [
  { label: 'Январь', value: 0 },
  { label: 'Февраль', value: 1 },
  { label: 'March', value: 2 },
  { label: 'April', value: 3 },
  { label: 'May', value: 4 },
  { label: 'June', value: 5 },
  { label: 'July', value: 6 },
  { label: 'August', value: 7 },
  { label: 'September', value: 8 },
  { label: 'October', value: 9 },
  { label: 'November', value: 10 },
  { label: 'December', value: 11 },
];
